quipucords/camayoc

MANIFEST.in
Makefile
README.rst
camayoc/__init__.py
camayoc/tests/__init__.py
docs/Makefile
docs/conf.py
docs/index.rst
setup.py
tests/__init__.py

Added three commits (_they are meant to not be squashed_):
* Update the README file to use RST instead of Markdown
* Add more metadata information on setup.py
* Create the automation framework directory structure with the camayoc package and the test packages for both RHO's functional tests and camayoc's unittests. Bonus created a Makefile to help with common tasks like running the unittests, linting, building docs and building the Python package.

Create the automation framework directory structure

---

.travis.yml

Test and lint Camayoc on Python 3.4+. Also publish the coverage report
on coveralls.
Closes #9

Add .travis.yaml file

---

camayoc/constants.py
camayoc/tests/conftest.py
camayoc/tests/rho/__init__.py
camayoc/tests/rho/test_auth.py
camayoc/utils.py
setup.py

Added some commits to get the initial test scenarios for `rho auth *` commands automated:
* Created a context manager to help creating a temporary directory. This will help ensure that the `data` directory created by RHO gets created and removed for every test.
* Added a py.test fixture which makes use of the isolated_filesystem context manager. Now whenever a test function has the `isolated_filesystem` argument py.test will automatically run the context manager and generate/remove the temporary directory.
* Added pexpect as a requirement it will help running RHO and filling its inputs like the vault password.
* Finally with all the above in place, we are able to automate some test cases. These automated tests should cover  the happy path and some negative tests for the `rho auth *` …

Add tests for rho auth add command

---

camayoc/constants.py
camayoc/tests/remote/__init__.py
camayoc/tests/remote/conftest.py
camayoc/tests/remote/rho/__init__.py
camayoc/tests/remote/rho/test_scan.py
docs/api.rst
docs/api/camayoc.tests.remote.conftest.rst
docs/api/camayoc.tests.remote.rho.rst
docs/api/camayoc.tests.remote.rho.test_scan.rst
docs/api/camayoc.tests.remote.rst
docs/api/camayoc.tests.rst

Includes a session-level fixture to turn on machines before tests run
and turn them off at end of session.
The scan test is parameterized on the profiles listed in config file,
and runs once per profile. In each profile, all hosts have known facts
compared to collected facts.
Updated docs to include new `remote` module.
Closes #24 
Closes #25 
Example config file:
```
#/home/user/.config/camayoc/config.yaml
rho:
auths:
- username: root
name: sonar
sshkeyfile: /home/elijah/.ssh/id_sonar_jenkins_rsa
hosts:
- hostname: string-name-of-vm-on-vcenter
ip: XX.XX.XXX.XX
provider: vcenter
facts:
connection.port: 22
cpu.count: 1
profiles:
- name: profile1
auths:
- auth1
hosts:
- XX.XX.XXX.XX
vcenter:
hostname: **Required** -- url to vcenter instance
username: **optional** -- will first try …
```

Add module to run tests on remote machines.

---

setup.py

Forgot this key part of making this work on someone else's machine 😬

Add pyvmomi package to dev requirements

---

camayoc/tests/remote/conftest.py

It takes time between the power on signal is sent to the remote servers
and they are available over ssh for rho. These changes make it so
servers are polled until they respond or a timeout limit is reached.
Closes #28

Poll remote servers until live.

---

camayoc/constants.py
camayoc/tests/rho/test_fact.py

Add the list of facts that RHO scan's for and update the fact related
tests to match for the exact match of the expected facts.
Closes #32

Assert for exact facts match on fact related tests

---

camayoc/tests/rho/test_scan.py

Add test_scan_with_facts parametrized test which perform a scan and
provide the `--facts` option, then assert if the generated report
includes only the expected facts.
Also update test_scan to assert for the expected implicit facts (when
`--facts` == '').
Closes #35

Add test to perform a scan for specific facts

---

.gitignore
scripts/gen_config.py

Provided a csv file with ip to profile to auth mapping (exapmle: "Test machines" tab of our Automation Test Matrix sheet), and a rho scan
csv file, gen_config.py will generate a new config file for you based on
your current config file (if it exists).
The new config file is placed in the $CWD and the user is left to do with it as they please.

Adds tool to generate config file

---

camayoc/tests/remote/rho/test_scan.py

Also, fixes problem of key errors if expected fact not present in scan,
will fail more gracefully with informative error message now.
Closes #40 
I ran the remote tests against the vcenter machines as well as against my local machine, and this fixed the key jboss fact key errors I was getting!
Once this is merged I will update jenkins config files so it will run tests against all facts.

Have remote tests scan all facts.

---

.travis.yml
Makefile
camayoc/tests/remote/rho/test_scan.py
camayoc/tests/rho/test_auth.py
camayoc/tests/rho/test_fact.py
camayoc/tests/rho/test_options.py
camayoc/tests/rho/test_profile.py
camayoc/tests/rho/test_scan.py
setup.py

Add caselevel field and update requirement value. Add Testimony as a dev
requirement and run `testimony validate` on Travis.
Closes #44

Update test docstrings for Rho tests

---

camayoc/tests/rho/test_auth.py
camayoc/tests/rho/test_profile.py

Update the tests to work with the new SSH key path validation for `rho
auth add` and `rho auth edit`.
Closes #57

Update rho auth and profile tests

---

camayoc/constants.py
camayoc/tests/rho/test_scan.py

Also update the rho scan tests to match the new set of facts depending
on the fact group passed to the `--facts` option when running a scan.
Closes #59

Update expected rho fact list

---

camayoc/tests/qcs/test_credentials.py
camayoc/tests/qcs/test_profiles.py

Capitalize the requirement name as it is the title of the requirement.

Capitalize quipucords requirement name

---

camayoc/tests/remote/rho/test_scan.py

Setting the test id for each test based on the profile it is testing
will make it easier to read the test results in Jenkins.
Eventually I want to parametrize on each fact, but that is going to require some not-so-obvious pytest finagling because you cannot directly parametrize based on results of a fixture (yet, this is a proposed feature)
Meanwhile, this will make jenkins a lot easier to decipher.

Make test results more readable

---

scripts/power_control.py

This script turns on all vcenter machines with the 'sonar-' prefix,
and it meant as a tool for developers.
Users may provide credentials via the CLI or in camayoc config file,
and any combination of the two is acceptable. The CLI will allways take
precedence over the config file.
Closes #63

Add script to turn on and off vcenter machines

---

camayoc/constants.py
camayoc/tests/remote/rho/conftest.py
camayoc/tests/remote/rho/test_scan.py
docs/api/camayoc.tests.remote.rho.conftest.rst
docs/api/camayoc.tests.remote.rho.rst
scripts/gen_config.py

@elyezer 
This "works" but has a couple rough points:
One is the fact that a lot of the jboss facts will come back '(...factname... not found)' if JBoss is in a location that the scan user cannot read. This is the case on most of our machines, but you would actually get the same data if the files were in directories that the scan user could read (like its home directory).
Also, I'm not sure if the underprivileged user will get the same count on jboss processes, it seems not but I'm not 100% sure this is a privilege issue, and I don't feel great about doing some kind of arithmetic on how many fewer jboss processes the user will find.
All in all, I think our test results will now provide a lot more insight as to how many facts we are having issues with when we see this:
``` …
```

Issues/56 Test facts based on privilege of auth

---

camayoc/constants.py

Closes #72 
@elyezer 
@noahl says that these should be in the "regular" jboss facts.
I need to do some testing to confirm that and see if these facts change with privilege level, but I'm having trouble completing a scan with what is in rho master right now.  (it is hanging on jboss_eap : look for jboss systemd service task)

Update fact list to include new jboss facts

---

camayoc/tests/remote/rho/conftest.py
camayoc/tests/remote/rho/test_scan.py

This removes the separate test parametrized on the profiles that did a
whole other scan on the systems to record that test result. Instead, the
result of the scan is stored as a fact called "scan performed" and we
get a test result for that fact based on whether or not the scan got
through the whole process and produced a report.

Avoid extra scan by storing scan result as fact

---

camayoc/tests/qcs/test_credentials.py

Make sure all tests that interacts with file system do that on an
isolated filesystem.

Add isolated_filesystem to some credentials tests

---

camayoc/constants.py
camayoc/qcs_models.py
camayoc/tests/qcs/test_scan.py
docs/api.rst
docs/api/camayoc.tests.qcs.rst
docs/api/camayoc.tests.qcs.test_scan.rst

Adds a class to represent Scans that allows you to create scans, check on their
status, and alter status (pause/restart/cancel).
Includes one test that is parametrized on profiles found in the config file
that runs the scan and checks to see that it completes and generates a fact
collection.
Marked this WIP because I make the wait_until_complete() function have a timeout, because I did encounter a situation where it seemed like the scan was stuck in pending and was not going to get promoted (which would be a bug, but need to figure out how to re-create it).

Add QSC object for scan and one scan test

---

camayoc/tests/qcs/test_profiles.py
camayoc/tests/qcs/utils.py

Adds tests for network profiles, including several "negative" test scenarios.
Also includes some minor refactor of existing tests to be consistent with other
modules use of camayoc.utils.uuid4 and to add objects to cleanup before other possibly exception throwing activity.

Automate Network Profile test stubs

---

camayoc/qcs_models.py
camayoc/tests/qcs/test_scan.py
tests/test_api.py

Updates several changes, including:
* ssh_port is now port for Sources
* Scans now take a list of sources
* Scans now take a dictionary of options
* Scans now have types 'connect' or 'inspect'

Update qcs tests to reflect API changes

---

camayoc/exceptions.py
camayoc/tests/qcs/test_scan.py

Automate test stubs in qcs test_scan module.
These tests include testing that scans can be paused and canceled, as
well that queues of scans progress even if some fail or are paused or
canceled.
Closes #83

Automate existing test scan stubs

---

camayoc/constants.py
camayoc/tests/qcs/api/v1/scans/test_network_scans.py
camayoc/tests/qcs/api/v1/scans/test_satellite_scans.py
camayoc/tests/qcs/api/v1/scans/test_vcenter_scans.py
camayoc/tests/qcs/api/v1/scans/utils.py
docs/api.rst
docs/api/camayoc.tests.qcs.api.v1.scans.rst
docs/api/camayoc.tests.qcs.api.v1.scans.test_satellite_scans.rst
docs/api/camayoc.tests.qcs.api.v1.scans.test_vcenter_scans.rst
docs/api/camayoc.tests.qcs.api.v1.scans.utils.rst

Adds test for vcenter and satellite.
NOTES:
* Satellite scans skip for now because they are not implemented yet.
* Facts collected by the vcenter scan cannot yet be accepted by the
server's fact endpoint, so we do not test for this -- but this should
be done eventually.
Closes #92
In addition, just to prolong this config file fun, I propose the following change (and this PR currently depends on it, though it can be changed):
Main proposal is to get rid of rho section and just have auths section, so rho will use auths and inventory and vcenter (for remote jobs) and quipucords will use auths, qcs, and vcenter for scans that don't need to control powerstate of vCenter vm's and then will use inventory when we get around to doing remote scan tests.
What do you think? Here is an example
```yaml …
```

Add tests/stubs for vcenter and satellite scans

---

.travis.yml
setup.py

pytest does not have the param function for its version available on
Python 3.4 and that is needed in order to xfail test data that is
related to bug. Also most of the current distros has Python 3.5+
installed.

Drop support to Python 3.4

---

camayoc/tests/qcs/cli/conftest.py
camayoc/tests/qcs/cli/test_sources.py
camayoc/tests/qcs/cli/utils.py
docs/api/camayoc.tests.qcs.cli.rst
docs/api/camayoc.tests.qcs.cli.test_sources.rst

Add initial qpc source tests

---

camayoc/constants.py
camayoc/tests/qcs/cli/test_sources.py

Update the tests to match the current quipucords version. This will make
all tests pass with the current quipucords master.

Update qpc source tests

---

camayoc/api.py
camayoc/constants.py
camayoc/tests/qcs/api/v1/authentication/__init__.py
camayoc/tests/qcs/api/v1/authentication/test_login.py
camayoc/tests/qcs/cli/conftest.py
docs/api.rst
docs/api/camayoc.tests.qcs.api.v1.authentication.rst
docs/api/camayoc.tests.qcs.api.v1.authentication.test_login.rst
docs/api/camayoc.tests.qcs.api.v1.rst
tests/test_api.py

Adds necessary code to api.Client to have the client send authenticated
requests if desired. This is enabled by default, but can be disabled
by calling api.Client().logout() or by passing a flag to the constructor
to disable it from the start. Also adds API login and logout tests.
Also has the CLI client login to the server after configuring the host
and port. This has the effect of all CLI tests being authenticated.
Negative tests for unauthenticated qpc commands and logout tests for the
CLI should be added at another time.
Closes #93

Make API and CLI tests authenticate

---

camayoc/tests/qcs/api/v1/reports/__init__.py
camayoc/tests/qcs/api/v1/reports/test_reports.py
docs/api.rst
docs/api/camayoc.tests.qcs.api.v1.reports.rst
docs/api/camayoc.tests.qcs.api.v1.reports.test_reports.rst
docs/api/camayoc.tests.qcs.api.v1.rst

Outline test cases for reports. Reports are still very much in flux and
we need some more details about what facts will be present, with what
priority they are chosen between sources when different information is
merged, and what queries to the reports endpoint will be acceptable.
That being said, this is a good start and gets the test cases in a
format so we can view them from our read the docs website.
Closes #95
Closes #94
Closes #98

Stub out tests for reports

---

docs/api.rst

Not all the CLI test cases were being published to the RTD page because
of missing declaration in docs/api.rst. Opened #126 remember to automate this
process.

Fix missing docs in sphinx build

---

camayoc/tests/qcs/cli/conftest.py

Configure qpc to use or not HTTPS

---

camayoc/constants.py
camayoc/qcs_models.py
camayoc/tests/qcs/api/v1/credentials/test_creds_common.py
camayoc/tests/qcs/api/v1/credentials/test_manager_creds.py
camayoc/tests/qcs/api/v1/credentials/test_network_creds.py
camayoc/tests/qcs/api/v1/scans/test_multi_source_scans.py
camayoc/tests/qcs/api/v1/scans/test_network_scans.py
camayoc/tests/qcs/api/v1/scans/test_satellite_scans.py
camayoc/tests/qcs/api/v1/scans/test_vcenter_scans.py
camayoc/tests/qcs/api/v1/sources/test_manager_sources.py
camayoc/tests/qcs/api/v1/utils.py
docs/api.rst
docs/api/camayoc.tests.qcs.api.v1.credentials.rst
docs/api/camayoc.tests.qcs.api.v1.credentials.test_manager_creds.rst
docs/api/camayoc.tests.qcs.api.v1.scans.rst
docs/api/camayoc.tests.qcs.api.v1.scans.test_multi_source_scans.rst
tests/test_api.py

Adds test cases that were missing because of missing functionality at
the original time of writing the tests. This includes:
- Tests for become methods with credentials
- Scans that scan multiple sources and source types
- A scan job that has a source that is expected to fail as well as a
source that should succeed
- Test case for satellite version options
Closes #130

Fix missing test cases in quipucords api tests

---

camayoc/api.py
camayoc/tests/qcs/cli/conftest.py

Make the API client verify HTTPS connection based on the configuration
file's ssl-verify option. Also centralize where the default headers are
set so it will be easy to update in the future if needed.
Close #136

Update API client

---

camayoc/qcs_models.py
camayoc/tests/qcs/api/v1/credentials/test_creds_common.py
camayoc/tests/qcs/api/v1/scans/test_multi_source_scans.py
camayoc/tests/qcs/api/v1/sources/test_sources_common.py
camayoc/tests/qcs/api/v1/utils.py
tests/test_api.py

Updates tests to allow the results of listing all credentials or sources to be
paginated. Also updates the equivlancy tests to set proper default values for
ssl_cert_verify and satellite version.
Closes #142

Update API tests to deal with pagination and new options

---

camayoc/tests/qcs/cli/utils.py

Updated rho tests to use the same config file format as quipucords, but forgot
to update qpc CLI tests to not use an extra field created to guard rho tests
from using some credentials.

Fix CLI tests to allow for new config data

---

camayoc/constants.py
camayoc/tests/qcs/api/v1/utils.py
camayoc/tests/qcs/cli/test_scans.py
camayoc/tests/remote/conftest.py
camayoc/tests/remote/quipucords/__init__.py
camayoc/tests/remote/quipucords/test_scan.py
camayoc/tests/remote/rho/test_scan.py
camayoc/tests/remote/utils.py
camayoc/utils.py
docs/api.rst
docs/api/camayoc.tests.remote.conftest.rst
docs/api/camayoc.tests.remote.quipucords.rst
docs/api/camayoc.tests.remote.quipucords.test_scan.rst
docs/api/camayoc.tests.remote.rst
docs/api/camayoc.tests.remote.utils.rst
docs/api/tests.test_utils.rst

Push vcenter client fixture up a level so it can be shared across rho/quipucords remote scans.
This would entail another :disappointed: update to the config file -- putting vcenter and satellite sources we want to scan down in the inventory, and associating creds directly with the items in the inventory.
Really, it only adds info to the config, so doesn't seem to be breaking anything yet. I've run the rho remote scan test and seems to be working, just needed minor tweak to get('hypervisor') instead of directly accessing it and the extra `credentials` key does not seem to matter. 
I've gotten my "minimum viable" scan to run with the following config:
```
---
credentials:
- name: root
type: 'network'
sshkeyfile: /sshkeys/id_sonar_jenkins_rsa
username: root
- name: 'vcenter'
type: 'vcenter' …
```

Scan remote systems Issues/148

---

camayoc/tests/remote/rho/test_scan.py

It appears this change in the type expected fell through the cracks with the
updates to the quipucords remote scans.
This appears to fix it based on local testing, where the error that the
automated jobs were having was reproducable.

Fix key error in rho remote scan

---

camayoc/tests/qcs/api/v1/credentials/test_creds_common.py
camayoc/tests/qcs/api/v1/sources/test_sources_common.py
camayoc/tests/qcs/conftest.py

Update existing tests and fixtures to deal with the fact that we must delete
all scans before we delete sources involved in them, and that we must delete
all sources before we delete credentials that depend on them.
Reworks how a couple tests work through paginated data from API because they
were failing to advance pages correctly.
Finally adds a test case confirming that we get denied if we attempt to delete
a credential if a source depends on it, and that we can then update the source
to use a new credential or we may delete the source and this then allows us to
delete the credential.
Closes #163

Test new delete workflow for credentials

---

camayoc/qcs_models.py
camayoc/tests/qcs/api/v1/sources/test_sources_common.py
camayoc/tests/qcs/utils.py
tests/test_api.py

Adds test cases for the new delete workflow that bars users from deleting
sources that are members of scans.
Also implements several pre-existing test stubs for sources.
Closes #165

Test new delete workflow for sources and flesh out other stubs

---

camayoc/tests/qcs/cli/conftest.py
camayoc/tests/qcs/cli/test_credentials.py
camayoc/tests/qcs/cli/test_scans.py
camayoc/tests/qcs/cli/test_sources.py
camayoc/tests/qcs/cli/utils.py

Adds cleanup_module fixture to clean up any credentials, sources, or scans
leftover after a module in the correct order to avoid causing spurious errors
in other tests now that users are blocked from deleting objects that other
objects depend on.
Updates expected output for satellite source show, because now the satellite
version is determined at run time and is not stored.
Closes #160

Update CLI scan tests to use new scan job and report workflow

---

camayoc/tests/qcs/cli/conftest.py
camayoc/tests/qcs/cli/test_scans.py
camayoc/tests/qcs/cli/utils.py

Use a for loop to clear the server on conftest and rename helper
functions to match the cli commands they are for.

Update qcs cli utils and conftest

---

camayoc/qcs_models.py
camayoc/tests/qcs/api/v1/scanjobs/test_run_scanjobs.py
camayoc/tests/qcs/api/v1/sources/test_manager_sources.py

The satellite version is now determined at runtime and this data is not stored
or exposed to the user.  This PR removes all tests that set and or checked the
satellite version of a satellite source.
Closes #152

Remove all references to satellite version

---

camayoc/qcs_models.py
camayoc/tests/qcs/api/v1/scanjobs/test_run_scanjobs.py
camayoc/tests/qcs/api/v1/utils.py

Now results for the connection and inspection tasks are available at seperate
endpoints.  Update test that was inspecting arithmetic for reached and
unreached hosts to get this data from the scan job detail, where it now lives.
Closes #181

Update to use new scan job results API

---

camayoc/tests/qpc/cli/utils.py

Increase the timeout to 60 seconds and call `pexpect.run` instead of
`pexpect.spawn`.

Improve the cli_command function

---

camayoc/qpc_models.py

The merge report was moved from /jobs/merge to /reports/merge. Update
the create_from_merge method to reflect that.

Update the API URL of create_from_merge method

---

camayoc/tests/qpc/cli/conftest.py
camayoc/tests/qpc/cli/test_reports.py
camayoc/tests/qpc/cli/utils.py

Added new tests for `qpc report download`.
Also, removed some unused packages to fix Travis builds.

add report download tests

---

camayoc/tests/qpc/cli/csv_report_parsing.py
camayoc/tests/qpc/cli/test_reports.py
camayoc/tests/qpc/cli/utils.py
setup.py

The header information of reports used to be hard-coded in, parsing the csv lines and binding them to specific variables. This caused the tests to break when a new field was added because there were more items parsed than variables to bind them to.
I've edited the csv parsing so that it is dynamically parsed into a dictionary that can then be used to create the report objects. I have added asserts so that if new fields are added, the tests will still fail to notify that it is out of date, but will just require at minimum adding the field to the expected list.
The process of normalizing the csv reports to what the json parsing returns has also been extracted to it's own set of the function, to clean up the actual tests a bit.
The one issue with this fix is that it still is hard coded to …

Refactor csv report parsing (fixes #303)

---

camayoc/tests/qpc/cli/test_reports.py

The 'vm_host_core_count' field has to be added to the expected summary report fields list.

Added 'vm_host_core_count' to expected summary fields

---

setup.py

Requiring `pydocstyle==3.0.0` until upstream bug is fixed.
Related:
https://gitlab.com/pycqa/flake8-docstrings/issues/36

dropped pydocstyle to 3.0.0 until upstream bug is fixed

---

camayoc/tests/qpc/yupana/test_connect.py
camayoc/tests/qpc/yupana/utils.py

Moved some of the `oc` helper functions from camayoc to `oc.utils`. This PR switches camayoc to import them from `oc.utils` now that they're in the `oc` install.

Switched to using multi search function added to oc.utils

---

README.rst
example_config.yaml

Added a `yupana` section to the README doc. It explains that to run the yupana tests, one has to first define the required parameters in the `config` file, under the `yupana` section. Then, the yupana tests can be run with `make test-qpc-yupana`.
I also added the required yupana configs to the example config file.
This documentation will expand in detail, and the config options may be cleaned up a bit as further work on the yupana test set progresses. This PR is mainly focused on making sure that the starting process of running the base yupana tests is documented.
Closes #318

Added a yupana section to the documentation

---

camayoc/inventory.py
camayoc/tests/qpc/yupana/conftest.py
camayoc/tests/qpc/yupana/utils.py
camayoc/utils.py
example_config.yaml

This module allows one to query the host based inventory, like this:
```Python
>>> from camayoc import config 
>>> from camayoc import inventory
>>> cfg = config.get_config()
>>> cfg['yupana']['inventory']
{'api_url': 'https://ci.example.com/api/inventory/v1/',
'rh_username': 'test',
'rh_password': 'example',
'rh_account_number': '000001',
'rh_org_id': '0000001'}
>>> cfg_inv  = cfg['yupana']['inventory']
```
Then we can get the whole host inventory as a list:
```Python
>>> auth = (cfg_inv['rh_username'], cfg_Inv['rh_password'])
>>> url = cfg_inv['api_url']
>>> inventory.get_hosts(url=url, auth=auth)
```
If something is wrong, then an exception of kind `RuntimeError()` will be raised.
There is also a function to query for a list of host ids, use `inventory.find_hosts` for that.
There is …

Add camayoc.inventory module - host based inventory

---

camayoc/tests/qpc/cli/test_reports.py

The `message` key parameter of `pytest.raises` [has been deprecated](https://docs.pytest.org/en/latest/deprecations.html#message-parameter-of-pytest-raises). This has caused some of the camayoc tests to fail recently.
This PR removes the `message` key parameter, and  adds the message as a `pytest.fail` message at the end of the `with pytest.raises` block, as suggested.
This fixes the tests failing due to this issue, and as such, closes issue #346.

Converted the pytest.raises 'message' keyparams to pytest.fail calls

---

camayoc/tests/qpc/api/v1/scanjobs/test_pause_cancel_restart.py
camayoc/tests/qpc/api/v1/scanjobs/test_run_scanjobs.py

We still had some tests randomly failing and passing depending on the run. They seem to fail due to complications related to known pause/restart issues. So, for the time being they will be skipped until working again.

Skipping flaky tests for now

---

camayoc/tests/qpc/api/v1/credentials/test_network_creds.py

Skip tests with hardcoded /sshkeys/ path locally and at the server.
We will figure out how to handle these tests later.
```
================================= test session starts ==================================
platform darwin -- Python 3.10.2, pytest-7.0.1, pluggy-1.0.0 -- /Users/rmoura/.virtualenvs/camayoc/bin/python3
cachedir: .pytest_cache
rootdir: /Users/rmoura/Developer/camayoc, configfile: pytest.ini
plugins: cov-3.0.0
collected 574 items / 559 deselected / 15 selected                                     
camayoc/tests/qpc/api/v1/credentials/test_network_creds.py::test_update_password_to_sshkeyfile SKIPPED [  6%]
camayoc/tests/qpc/api/v1/credentials/test_network_creds.py::test_update_sshkey_to_password SKIPPED [ 13%]
camayoc/tests/qpc/api/v1/credentials/test_network_creds.py::test …
```

Skip tests with hardcoded /sshkeys/ path

---

camayoc/tests/qpc/api/v1/sources/test_network_sources.py
camayoc/tests/qpc/cli/test_credentials.py

Skip tests with the same hardcoded `/sshkeys/` path locally and at the server.

Skip more tests with hardcoded /sshkeys/ path

---

camayoc/tests/qpc/api/v1/credentials/test_network_creds.py
camayoc/tests/qpc/api/v1/sources/test_network_sources.py
camayoc/tests/qpc/cli/test_credentials.py

Since we assume Camayoc will execute in the same machine as
the server, then we don't need to skip tests due local sshkeys anymore.

Revert changes to SKIP_REASON_LOCAL_SSHKEYS

---

camayoc/tests/qpc/cli/test_scanjobs.py

Increase wait_for_scan() time to 30 minutes (1800 seconds),
to avoid to have the test_scanjob timed out in longer scan executions.

Set timeout to 1800s for qpc.cli.test_scanjobs.test_scanjob

---

camayoc/tests/qpc/cli/test_reports.py

Adapt tests for the changes introduced in quipucords/quipucords#2169
More context on [this comment](https://github.com/quipucords/quipucords/pull/2169#issuecomment-1175619760)
NOTE: because downstream doesn't return the same fact list merging this PR will cause the affected tests to break tests on downstream until these changes are released.

[DISCOVERY-21] Update json deployment report fields

---

camayoc/tests/qpc/ui/test_endtoend.py
camayoc/tests/qpc/ui/test_playwright_demo.py
camayoc/tests/qpc/utils.py
camayoc/ui/models/components/logged_in.py
camayoc/ui/models/mixins.py
camayoc/ui/models/pages/scans.py
docs/Makefile

This PR includes / builds upon #365 . Story is similar to #369 - I can include this in #365 , or we can close #365 and continue discussion here, or I can rebase this once #365 is merged.
This is parallel to #369 and one should nicely rebase on top of another. I didn't include one in another to indicate that this is largely independent work.
This introduces proper end-to-end UI tests. For each source type (Network, Satellite and vCenter), it executes following path:
1. Login
2. Create credential
3. Create source
4. Trigger scan
5. Download report
6. Logout
7. Run assertions on report
Created data is later removed using API, so we should be able to run test repeatedly without leaving too much rubbish behind.
Input data for forms may be specified inside function. I have done this for Network …

Proper end to end tests utilizing Playwright

---

.pre-commit-config.yaml
pytest.ini

* pytest: silence warnings regarding "pytest.mark.ssh_keyfile_path"
* pre-commit: get flake8 from github + update refs

Maintenance: pytest warnings and flake8

---

docs/development.rst
docs/development/openshift.rst
example_config.yaml
scripts/openshift_deploy.yaml

Creates an Ansible Playbook for provisioning an OpenShift (OCP) project for inspection.
Note: gave up using ocp modules for Ansible since most of them are deprecated. People are using community.k8s nowadays, but using shell with oc instead gave more freedom.
Co-authored-by: Ruda Moura <rmoura@redhat.com>

Creates an Ansible Playbook for OpenShift project deployment

---

camayoc/tests/qpc/utils.py

Error messages received when trying to create source changed, causing tests to fail.
I update all messages in one go, as 2 of them are checked in one test, and another in next one. But since all are next to each other, I think it's cleaner this way.
```
$ RUN_SCANS=False pytest -v -s 'camayoc/tests/qpc/api/v1/sources/test_manager_sources.py::test_negative_create_multiple' 'camayoc/tests/qpc/api/v1/sources/test_sources_common.py::test_create_exclude_hosts_negative'
camayoc/tests/qpc/api/v1/sources/test_manager_sources.py::test_negative_create_multiple[vcenter-scan_host0] PASSED
camayoc/tests/qpc/api/v1/sources/test_manager_sources.py::test_negative_create_multiple[vcenter-scan_host1] PASSED
camayoc/tests/qpc/api/v1/sources/test_manager_sources.py::test_negative_create_multiple[satellite-sca …
```

Update error messages received during source creation

---

camayoc/tests/qpc/cli/test_sources.py

Pytest execution (snippet).
```
E               0: re.compile(b'exclude_hosts: The exclude_hosts option is not valid for source of type satellite.')
/Users/rmoura/Developer/camayoc/.venv/lib/python3.11/site-packages/pexpect/expect.py:122: EOF
=================================== short test summary info ====================================
FAILED camayoc/tests/qpc/cli/test_sources.py::test_add_exclude_hosts_negative[vcenter-192.168.0.42-192.168.0.43] - pexpect.exceptions.EOF: End Of File (EOF). Empty string style platform.
FAILED camayoc/tests/qpc/cli/test_sources.py::test_add_exclude_hosts_negative[satellite-192.168.0.42-192.168.0.43] - pexpect.exceptions.EOF: End Of File (EOF). Empty string style platform.
```
The qpc error message has changed for the exclude_hosts option.
```
$ qpc …
```

Update error message for the exclude_hosts option when testing sources with CLI

---

camayoc/tests/conftest.py

We would like Ibutsu dashboard to show rows for CLI, API and UI. To do that, we need to set `component` field in result object.
However, that field can't be set using command line. So we have to use custom pytest hook.
If pytest-ibutsu is not installed, none of this will be executed.
Side note: Jenkins calls pytest with 
```
--ibutsu-data discovery=${DISCOVERY_RELEASE} camayoc=1.0.0 dsc=${DISCOVERY_RELEASE} jenkins_job_number="${BUILD_NUMBER}"
```
`camayoc` field _could_ be set up using hook from this PR, but we would need to solve [Single-sourcing the package version](https://packaging.python.org/en/latest/guides/single-sourcing-package-version/) first.

Set Ibutsu component automatically based on test location

---

camayoc/tests/qpc/api/v1/sources/test_network_sources.py

Basically, the same thing as #386 and #387, but on another test.
This test creates a bunch of credentials, then creates a source and tries to update source to become invalid. There's no particular reason to use SSH key-backed credential specifically, we only need a valid credential.
```
$ pytest -v -ra 'camayoc/tests/qpc/api/v1/sources/test_network_sources.py::test_negative_update_invalid'
camayoc/tests/qpc/api/v1/sources/test_network_sources.py::test_negative_update_invalid[localhost] PASSED                                                               [ 33%]
camayoc/tests/qpc/api/v1/sources/test_network_sources.py::test_negative_update_invalid[127.0.0.1] PASSED                                                               [ 66%] …
```

Fix test_negative_update_invalid

---

camayoc/tests/qpc/cli/test_credentials.py

All these tests failed during setup / arrange phase, while trying to create credentials that used SSH keys for authentication. I _think_ the reason for this design choice was that SSH key-backed credentials can be created in unattended way, while password-backed credentials can't - user is prompted to enter password. But the helper **already** supports prompts, and did so from day 1. So we don't have to resort to SSH keys, which have specific infrastructure requirements.
Also remove `auth` variable from test_clear_all, which never did anything and probably is a leftover of some idea that never get implemented.
Tests fixed:
- test_edit_username_negative
- test_edit_password_negative
- test_edit_become_password
- test_edit_become_password_negative
- test_edit_no_credentials
- test_clear
- …

Fix multiple credentials CLI tests

---

.github/workflows/docs.yml
.github/workflows/tests.yml
Makefile

Update codecov to Github Action. See #392 and https://about.codecov.io/blog/message-regarding-the-pypi-package/ .
I needed to create new repository secret named `CODECOV_TOKEN`.
Personally I don't see much value in codecov and would be fine dropping it altogether, but that's another discussion - for now, let's focus on ensuring that CI passes.

Update codecov to GitHub Action

---

camayoc/tests/qpc/cli/test_sources.py

Based on discussion in DISCOVERY-286 - add Satellite to this test coverage.
Also, update expected error message - it was changed in https://github.com/quipucords/quipucords/commit/13ae8a1d3fe449844b82224813cb465155c6c41e .
The point of DISCOVERY-286 is that there's legitimate change in behavior, so these tests are currently failing anyway. There might be more changes needed as DISCOVERY-286 is fixed.

DISCOVERY-286: Add satellite to coverage

---

camayoc/config.py
camayoc/tests/qpc/cli/test_scans.py
camayoc/tests/qpc/cli/test_sources.py
camayoc/types/settings.py
camayoc/utils.py

cli executable might not be exactly what will appear on usage messages (for instance, if cli command is an absolute path and or an option is added to qpc - like `-v`).
For this reason I'm adding the extra setting.

feat: add setting for qpc "package name"

---

camayoc/tests/qpc/api/v1/sources/test_sources_common.py
camayoc/tests/qpc/cli/utils.py

With the changes proposed here, all CLI tests will pass as long the setting for executable is set to `qpc -v`.
Also requires changes proposed on quipucords/qpc#230 and quipucords/quipucords#2331
NOTE: we should choose between this, #394 or #398

Fix CLI tests with verbosity implicit

---

camayoc/constants.py
camayoc/tests/qpc/cli/test_openshift.py
camayoc/tests/qpc/cli/utils.py

Fix: DISCOVERY-281.
An OpenShift cluster is one or more instances belonging to a single product installation.  An instance is a host or VM running in the cloud. Each cluster will have a unique name called the `cluster_id`.
The objective of this test is to verify if Quipucords is performing OpenShift (OCP) inspection and collecting correct facts at the level of clusters and nodes.
Camayoc config.yaml for openshift with cluster and nodes.
```yaml
openshift:
- hostname: api.sharedocp4upi412ovn.example.com
port: 6443
token: 'sha256~...'
skip_tls_verify: true
cluster_id: '97c44acf-e8f1-46eb-b6a5-6ed78ecf2659'
version: '4.12.5'
nodes: 6
hosts:
- 'master-0.sharedocp4upi412ovn.example.com'
- 'master-1.sharedocp4upi412ovn.example.com'
- 'master-2.sharedocp4upi412ovn.example.com'
- …
```

DISCOVERY-281 - Add test coverage for OCP Clusters and Nodes

---

camayoc/types/settings.py
example_config.yaml

This fix completes the missing parameters for OpenShift inspection and validation. It will need further changes to adapt to the configuration style suggested in PR #389 . Relates to JIRA: DISCOVERY-281.

Fix test coverage for OCP Clusters and Nodes

---

.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/tests.yml
setup.cfg

RHEL9.2 and UBI9 has `Python 3.11` available to install.
Let's start to test Camayoc with Python 3.11 in the workflows.

Add Python 3.11 to the workflows

---

camayoc/data_provider.py
camayoc/exceptions.py
camayoc/qpc_models.py
setup.cfg
tests/test_data_provider.py

This is a **proposal** of new data providing facility. It's far from complete, but it _may_ work for certain cases and I feel it's complete _enough_ to enable discussion about something tangible.
This is fundamental framework work that - once completed - will enable us to tackle DISCOVERY-293. As it turned out, it will also enable to mostly tackle DISCOVERY-284. In other words, with this done, we will be set up to run **all** API and CLI tests in CI.
Commit 2f62d0f0e42684dd5acb04442b8798640015f9d1 is for illustrative purposes only. I will remove it before opening PR for merge.
The basic assumption is that most of the time, tests want data that is valid, and that can be safely removed afterwards. Sometimes tests want only data (i.e. negative object creation tests), sometimes they want …

Add data provider

---

camayoc/constants.py
camayoc/tests/qpc/cli/test_sources.py

The output message for qpc CLI has changed for displaying the values that the client accept regarding the boolean choices. Fix the tests and making all green.
Refactor: move valid boolean choices and SSL protocols to constants.
Reference: https://github.com/quipucords/qpc/commit/936e9636e1c3be46ea4a41c503c0208fa2d8e18b

CLI: Update tests that depends on the Boolean choices output message

---

README.rst
pyproject.toml

Pin Python to version 3.11 because the greenlet 2.0.2 module is not building in Python 3.12.
```
Package operations: 31 installs, 0 updates, 0 removals
• Installing greenlet (2.0.2): Failed
...
gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -I/tmp/tmpk10kzdgn/.venv/include -I/usr/include/python3.12 -c src/greenlet/greenlet.cpp -o build/temp.linux-x86_64-cpython-312/src/greenlet/greenlet.o
In file included from src/greenlet/greenlet_internal.hpp:20,
from src/greenlet/greenlet.cpp:19:
src/greenlet/greenlet_greenlet.hpp: In member function ‘void greenlet::PythonState::operator<<(const PyThreadState*)’:
src/greenlet/greenlet_greenlet.hpp:831:41: error: ‘_PyCFrame’ …
```

Restrict Python to 3.11.z in pyproject.toml

---

scripts/create-camayoc-ocp-config.py

"""Create an OpenShift configuration for Camayoc.                                                                                                                                
Given an OpenShift instance with credentials and URL to login,                                                                                                                   
this program will create a Openshift configuration for Camayoc.                                                                                                                  
Example:
Running...
```bash                                                                                                                                                             
./create-camayoc-ocp-config.py \ …
```

Add script to create OCP configs

---

camayoc/types/settings.py
camayoc/types/ui.py

Camayoc seems to accept a single port configuration for sources, the data model requires to provide the optional port number, this PRR adds this option.

Enable source port configuration

---

camayoc/tests/qpc/cli/test_credentials.py

This change supports https://github.com/quipucords/quipucords/pull/2735

fix: allow read-only "auth_type" attribute on credential API response

---

.github/workflows/tests.yml
codecov.yml

Yet another sibling to https://github.com/quipucords/qpc/pull/360 and https://github.com/quipucords/quipucords/pull/2824 so that all quipucords projects follow the same coverage requirements.
This config basically says:
* For the diff, require 80% coverage to pass the PR check.
* For the overall project, target the previous/parent commit's recorded coverage, but allow it to dip by 5% before it fails the PR check.
* The "range" value is purely aesthetic, IIUC. Files under 70% show as red, under 90% as yellow, and over 90% as green when viewed on codecov's website.

refactor: add codecov.yml config to override defaults

---

camayoc/tests/qpc/cli/test_openshift.py
camayoc/tests/qpc/cli/test_rhacs.py
camayoc/tests/qpc/cli/test_scanjobs.py
camayoc/tests/qpc/cli/utils.py

Notes:
* ~~I will rebase and squash the commits before it get merged~~ I rebased and squashed the commits.
* This PR requires coordination in order to avoid breaking the pipelines.
This PR will make the CLI default scan timeout set to Camayoc's configuration defined in `camayoc.scan_timeout`. Also, the `ui` tests are already using this default value from the configuration.
Rationale: Many CLI tests are already using hardcoded 20 minutes (1200 seconds) timeout as default. Let's make it more flexivel and define this on a configuration. This will allows us to set the default scan timeout as we wish in different pipelines.
Relates to:
* https://github.com/quipucords/camayoc/blob/main/camayoc/config.py#L21
* https://github.com/quipucords/camayoc/blob/main/camayoc/types/settings.py#L15
* …

wait_for_scan: CLI default scan timeout comes from camayoc.scan_timeout configuration

---

pyproject.toml

Corresponds with https://github.com/quipucords/quipucords/pull/2977 and https://github.com/quipucords/qpc/pull/376 updates to allow uv 0.7+.

build: drop uv version restrictions
