- docs/index.rst
- docs/test_scenarios.rst
The rendered version of the test scenarios can be seen here https://github.com/quipucords/camayoc/blob/issues/2/docs/test_scenarios.rst.
Closes #2
> Add initial test scenarios to the docs

- camayoc/cli.py
- camayoc/exceptions.py
- camayoc/utils.py
- setup.py
- tests/test_cli.py
> Add cli module to help running CLI commands

- camayoc/tests/rho/test_profile.py
> Add tests for rho profile commands.

- camayoc/tests/rho/test_profile.py
Make sure rho profile add and edit accept hosts range in CIDR notation
too.
Closes #20
> Add tests for hosts range in CIDR notation

- camayoc/tests/rho/test_profile.py
Make sure `rho profile add` and `rho profile edit` commands accepts a
file as the `--hosts` value and the contents of that file will be set as
the hosts value.
Closes #22
> Add tests to add/edit a profile with a hosts file

- camayoc/tests/rho/test_fact.py
> Add test to filter facts using a regex

- Makefile
- scripts/validate_docstrings.sh
> Add script to validate test docstrings

- camayoc/constants.py
- camayoc/tests/rho/test_fact.py
- camayoc/tests/rho/test_scan.py
Update the expected facts to the ones rho is currently scanning for.
Closes #61
> Update rho fact list tests

- camayoc/api.py
- camayoc/qcs_models.py
- camayoc/tests/qcs/conftest.py
- camayoc/tests/qcs/test_credentials.py
- camayoc/tests/qcs/test_profiles.py
- camayoc/tests/qcs/utils.py
- docs/api/camayoc.tests.qcs.rst
- docs/api/camayoc.tests.qcs.utils.rst
- tests/test_api.py
I ended up working on both of these issues while I was travelling today, so they ended up on same branch because my work in the first commit introduced alot of breaking changes with the original layout I had.
This removes QCSClient and delegates all the interaction with the different endpoints to the QCSObjects themselves. I also added more tests.
The second commit stubs out more test cases.
I wanted to get this PR made so if you want to write some tests, we can move forward with this style.
> Issues 51 and 52

- camayoc/constants.py
Rename two jboss facts and add new redhat-packages.gpg facts.
> Update jboss facts and add new rhel facts

- camayoc/qcs_models.py
- camayoc/tests/qcs/test_credentials.py
> Automate quipucords host credential tests

- scripts/power_control.py
Will default to matching machines with 'sonar' in the name, otherwise will use
user specified pattern.
This was a small change that helped me use this script to turn on just a few machines from the command line.
Open to suggestions.
> Let user specify string to match for power control script

- camayoc/constants.py
- camayoc/qcs_models.py
- camayoc/tests/qcs/test_scan.py
See https://github.com/quipucords/quipucords/issues/229
@kholdaway says that the network profile endpoint update should land today so might wait to merge this until that happens
> Update credentials endpoint path

- camayoc/constants.py
> Add new jboss facts

- camayoc/tests/qcs/cli/__init__.py
- camayoc/tests/qcs/cli/conftest.py
- camayoc/tests/qcs/cli/test_credentials.py
- camayoc/tests/qcs/cli/utils.py
- docs/api/camayoc.tests.qcs.cli.conftest.rst
- docs/api/camayoc.tests.qcs.cli.rst
- docs/api/camayoc.tests.qcs.cli.test_credentials.rst
- docs/api/camayoc.tests.qcs.cli.utils.rst
- docs/api/camayoc.tests.qcs.rst
> Add tests for qpc credentials

- camayoc/api.py
- camayoc/exceptions.py
- tests/test_api.py
- tests/test_config.py
> Update how API client reads config file information

- camayoc/tests/qcs/cli/test_credentials.py
Update the tests so they pass after the issue quipucords#330 being
resolved.
Close #111
> Update cli test_credentials tests

- camayoc/constants.py
- camayoc/tests/qcs/cli/test_credentials.py
- camayoc/tests/qcs/cli/test_sources.py
- camayoc/tests/qcs/cli/utils.py
Update tests to match the current qpc state.
> Update qpc cli tests

- camayoc/tests/qcs/cli/test_credentials.py
Update tests to test other types than network only.
Close #128
> Update CLI crendentials tests to include the type

- camayoc/tests/qcs/cli/test_sources.py
Sources now have a new field called options. That is only set for
satellite type of sources currently to specify the satellite version.
Update the tests to match the new output.
Close #127
> Update qpc source tests because the new output

- camayoc/tests/qcs/cli/test_sources.py
Consider the new ssl_cert_verify field when expecting source show output
for satellite and vcenter.
Close #138
> Update CLI sources tests

- camayoc/tests/qcs/cli/test_credentials.py
- camayoc/tests/qcs/cli/test_sources.py
> Update CLI test_clear_all sources

- camayoc/tests/qcs/api/v1/scans/test_network_scans.py
- camayoc/tests/qcs/cli/test_scans.py
- camayoc/tests/qcs/cli/utils.py
- docs/api.rst
- docs/api/camayoc.tests.qcs.cli.rst
- docs/api/camayoc.tests.qcs.cli.test_scans.rst
> Add initial CLI scan tests

- camayoc/tests/remote/rho/test_scan.py
Updates how credentials are read from the config file so all portions of
camayoc can share a config file.
Closes #110
> Update rho tests to use same config file as qcs

- .travis.yml
- README.rst
> Migrate from coveralls to codecov

- camayoc/api.py
- tests/test_api.py
This change adds more information about the request and the response to the
HTTPError message raised by both the code_handler and the json_handler.
This should make the logs from the automated test runs more informative.
Closes #153 
Sample error message for 400 response:
```
HTTPError: 
============================================================
The request you made received a status code that indicates
an error was encountered. Details about the request and the
response are below.
============================================================
request path : '/api/v1/credentials/'
request body : (b'{"name": "808c8c19-e502-4af7-bd92-c5fbf45d3891", "username": "fb419524-c8e5-'
b'4960-812a-a2acf3259e76", "password": null, "ssh_keyfile": null, "cred_type":'
b' null}')
request headers : …
```
> Make error message returned by api client more informative

- setup.py
> Add pytest-selenium to required packages

- setup.py
Need this for the login test to be able to run
> Update missing pytest-selenium package

- camayoc/tests/qcs/api/v1/scans/test_scans_common.py
Test that the user cannot provide non-booleans to disable optional products.
It is the case that 'yes' and 'no' are valid booleans.
It is still the case that the server ignores extra input, this is a known
behavior, so we certainly can try and disable nonoptional products or
nonexistant ones, but the server will just ignore that input. This is not
considered a bug at this time.
Closes #171
> Add negative test case for disabled optional products

- camayoc/tests/qcs/api/v1/scanjobs/test_run_scanjobs.py
I'm putting this up here because I'm running into problems and could use some advice. @elyezer maybe we can talk about this on Monday or Tuesday next week?
> Assert products identified as "present" are expected to be found Issues/76

- camayoc/tests/qcs/cli/test_scans.py
> Add negative CLI test for scan actions

- camayoc/tests/qpc/cli/conftest.py
- camayoc/tests/qpc/cli/test_reports.py
- camayoc/tests/qpc/cli/test_scanjobs.py
- camayoc/tests/qpc/cli/utils.py
- docs/api.rst
- docs/api/camayoc.tests.qpc.cli.test_reports.rst
> Add tests for CLI scan reports

- camayoc/tests/qpc/cli/test_sources.py
--exclude-hosts is only valid for network source types, not vcenter or satellite, so this verifies that the test passes.
> Created test for invalid source types for --exclude-hosts

- camayoc/tests/qpc/ui/test_credentials.py
- camayoc/tests/qpc/ui/utils.py
Resolves #270 
Includes optional parameter tests and SSH keyfile tests
> Tests for credentials page

- .travis.yml
- camayoc/tests/qpc/ui/conftest.py
- camayoc/tests/qpc/ui/test_credentials.py
- camayoc/tests/qpc/ui/test_sources.py
- camayoc/tests/qpc/ui/utils.py
> 272 sources ui tests

- camayoc/tests/qpc/ui/conftest.py
- camayoc/tests/qpc/ui/test_credentials.py
- camayoc/tests/qpc/ui/test_login.py
- camayoc/tests/qpc/ui/utils.py
> New editing credential test, remove workaround for login test

- camayoc/tests/qpc/ui/conftest.py
- camayoc/tests/qpc/ui/test_credentials.py
- camayoc/tests/qpc/ui/utils.py
> Edit credential tests, debug mode fix

- camayoc/tests/conftest.py
- camayoc/tests/qpc/api/v1/conftest.py
- camayoc/tests/qpc/api/v1/utils.py
- camayoc/tests/qpc/conftest.py
- camayoc/tests/qpc/utils.py
- camayoc/tests/utils.py
Fetch vCenter machines' IP addresses on the fly by using VMWare Tools.
Also only turn on machines that will be scanned instead of turning all
machines.
> Improve API scans

- camayoc/exceptions.py
- camayoc/tests/qpc/cli/test_reports.py
- camayoc/tests/qpc/cli/utils.py
- docs/conf.py
* Update merge report tests to monitor the async merge task.
* Update the expected output of some report related commands.
* Update the expected report facts.
> Update CLI report tests

- camayoc/constants.py
- camayoc/tests/qpc/api/v1/reports/test_reports.py
- camayoc/tests/qpc/cli/test_scanjobs.py
Skipping a few tests until the known issues that cause them to fail are resolved. 
(Also fixed a `jboss` typo in one of the constants)
> Add skip tests

- setup.cfg
This version focuses on UI testing framework that uses Playwright.
> Camaoyc version 1.0.0

- camayoc/tests/qpc/ui/test_credentials.py
- camayoc/tests/qpc/ui/test_login.py
- camayoc/tests/qpc/ui/test_sources.py
Port the old ui tests (those who uses Selenium) to use and run on the new framework (that is based on Playwright).
* test_login
* test_credentials
* test_sources
> DRAFT: Port UI tests

- camayoc/tests/qpc/api/v1/credentials/test_network_creds.py
This is mirroring #386 , and the same reasoning applies here.
This really tests data validation during credential update. We need to create credential during arrange phase, but there is no particular reason why this credential should use SSH key specifically. Given infrastructure requirements around SSH keys, it's better to switch to plain old password authentication.
The neat part is that "you can't have both SSH key and password" validation is run before "does this SSH key exist", so we can pass any string in SSH key field and everything will still work.
```
$ pytest -v -ra 'camayoc/tests/qpc/api/v1/credentials/test_network_creds.py::test_negative_update_to_invalid'
camayoc/tests/qpc/api/v1/credentials/test_network_creds.py::test_negative_update_to_invalid PASSED …
```
> Fix test_negative_update_to_invalid

- camayoc/tests/qpc/cli/test_scans.py
Adding client cmd name for a test that was not caught on #396
> add missing client_cmd_name

- CONTRIBUTORS.rst
How?
* git log --format='%an <%ae>' | sort | uniq
* Manually grouping usernames
* Update Red Hat email for all
> Add CONTRIBUTORS

- AUTHORS.rst
- setup.cfg
Let's called it v1.2.5 plus AUTHORS file.
> Camayoc version 1.2.5

- camayoc/tests/qpc/cli/test_reports.py
Add "detection-acs" as a expected CSV_DEPLOYMENTS_REPORT_FIELDS.
> test(acs): add acs-detection to report tests

- camayoc/tests/qpc/cli/test_reports.py
This new fact is added to quipucords via:
https://github.com/quipucords/quipucords/pull/2480
Related to JIRA: DISCOVERY-422
https://issues.redhat.com/browse/DISCOVERY-422
> feat: add support for new installed_products fact

- camayoc/qpc_models.py
- camayoc/tests/qpc/cli/test_credentials.py
Adjust tests to reflect the addition of the new fields created_at and updated_at to the CRedential model.
> fix(credential): add new fields to Credentials

- camayoc/tests/qpc/cli/test_credentials.py
The output of "cred clear --all" will change as of https://github.com/quipucords/qpc/pull/316
Relates to JIRA: DISCOVERY-468
> fix: update expected output of "cred clear --all" command

- camayoc/exceptions.py
- camayoc/tests/qpc/cli/test_reports.py
- camayoc/tests/qpc/cli/utils.py
Relates to JIRA: DISCOVERY-452
> test report upload
